let list_data = [
  
  {
	author:'葛飞扬',
    date: '2018 04 09',
    title: '丢失一只苹果手机',
    detail_img: '../../images/other/iphone_x.jpg',
    avatar: '/images/avatar/4.png',
    detail_content: '4月9号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 88,
    attention_count: 66,
    name:'葛飞扬',
	phone:'15987654321',
	addr:'江苏理工学院南苑',
    postId: 0
  },
  {
    author:'罗一',
    date: '2018 04 08',
    title: '丢失一只三星s10',
    detail_img: '../../images/other/s10.jpg',
    avatar: '/images/avatar/0.png',
    detail_content: '4月8号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 3,
    attention_count: 36,
    name:'罗一',
	phone:'18912345678',
	addr:'江苏理工学院西苑',
    postId: 1
  },
  {
	author:'宋祥正',
    date: '2018 04 07',
    title: '丢失一只锤子r1',
    detail_img: '../../images/other/r1.jpg',
    avatar: '/images/avatar/1.png',
    detail_content: '4月7号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 2,
    attention_count: 68,
    name:'宋祥正',
	phone:'17387654321',
	addr:'江苏理工学院北苑',
    postId: 2
  },
  {
	author:'生力',
    date: '2018 04 06',
    title: '捡到小米mix3',
    detail_img: '../../images/other/mix3.jpg',
    avatar: '/images/avatar/2.png',
    detail_content: '4月6号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 6,
    attention_count: 94,
    name:'生力',
	phone:'17766239556',
	addr:'江苏理工学院体育馆',
    postId: 3
  },
  {
	author:'陆康康',
    date: '2018 04 05',
    title: '捡到谷歌pixel 3xl',
    detail_img: '../../images/other/pixel3xl.jpg',
    avatar: '/images/avatar/3.png',
    detail_content: '4月5号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 9,
    attention_count: 108,
    name:'陆康康',
	phone:'15513245678',
	addr:'江苏理工学院60号楼',
    postId: 4
  },
  {
	author:'周文涛',
    date: '2018 04 04',
    title: '捡到一加6T',
    detail_img: '../../images/other/onePlus6T.jpg',
    avatar: '/images/avatar/5.png',
    detail_content: '4月4号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 11,
    attention_count: 113,
    name:'周文涛',
	phone:'15513245678',
	addr:'江苏理工学院65号楼',
    postId: 5
  },
  {
	author:'段双全',
    date: '2018 04 03',
    title: '捡到华为P30 pro',
    detail_img: '../../images/other/p30_pro.jpg',
    avatar: '/images/avatar/6.png',
    detail_content: '4月3号本人于南苑操场丢失iPhone x一部，亮黑色，可能丢失地点为，篮球架和操场周围的马路，草丛。我已经仔细寻找多次，未曾找到。望捡到手机的好心人及时联系我，必有重谢！！！联系方式如下：',
    detail_love_image1: '../../images/template/star.png',
    detail_love_image2: '../../images/template/view.png',
    love_count: 15,
    attention_count: 106,
    name:'段双全',
	phone:'15999999999',
	addr:'江苏理工学院25号楼',
    postId: 6
  },
];

module.exports = {list_data};